### PR TITLE
[feat/Transformers]: Convert compute_metrics function into a Config dictionary.

### LINKED ISSUE #5: [Transformers]: Convert `compute_metrics` function into a Config dictionary.
## Description

Convert the compute metrics function into a dictionary config of composable functional transforms that can be passed to `peg_transformers.trainer.trainer___init__()`.

For example, the following piece of code
```python
metric = peg_evaluate.text_classification_evaluator___init__(default_metric_name="accuracy")


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return peg_evaluate.text_classification_evaluator_compute(
        metric, predictions=predictions, references=labels
    )
```

can be expressed as 
```json
{
  "metric_name": "accuracy",
  "logit_transforms": [
    {
      "function": "numpy.argmax",
      "kwargs": {"axis": -1}
    },
  ],
  "label_transforms": []
}
```

### PR DESCRIPTION
**Pull request by soumik12345**
Fixes https://github.com/AsokAI/pegasus/issues/5

### CODE REVIEW

**Comment by shivance** [comment]
This is LGTM!

**Review by kanpuriyanawab — APPROVED** [review]

**Comment by soumik12345** [comment]
@shivance Doesn't this PR remove any dependency from the `peg_transformers.evaluate` module?

**Review by arindas — APPROVED** [review]
Everything looks alright!

**Review by mratanusarkar — APPROVED** [review]
LGTM

**Pull request merged**
